development:
  adapter: mysql2
  encoding: utf8
  database: prevac_mqi
  pool: 5
  host: localhost
  username: root
  password: root
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: prevac_mqi_prod
  pool: 5
  host: localhost
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
