# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f36c73977e92b19582985877e4a4c6dc2b6dafee582ddc5c8f4b340eb57454c470a998f2a19fa31f611bb2cdc171614f2ed0b0fe90d6fd2e61f1fb22365514f6

test:
  secret_key_base: acd75398c6680be58c4447e9d8180b73982f39ae86e9af4ed667c12749b89c356f5b97ca8051bf7389edaec4f1eeb3bac625013e1afecd4b9fa718c4020e289e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 5a5dafcc66fc784ba2b53486477bf8c25dff79624a5b99d7cf725e70fd4ac1a027e85b70c30c03e60f86089a8c2df305d2b205239b2bd90f9b277c5ed7f4034f
